Repository k8ssandra/k8ssandra, pull requests merged in 2020-12, with the labels that each got.

#103 [GH 102] update medusa-operator image
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra-cluster/templates/medusa-operator/deployment.yaml
  charts/k8ssandra/Chart.yaml
  charts/restore/Chart.yaml
Labels: complexity: low

#53 Modify reaper configuration to use CassandraDatacenter
  charts/k8ssandra-cluster/templates/reaper.yaml
  charts/k8ssandra/crds/reaper/reaper.yaml
Labels: complexity: low

#98 Allow setting autoscheduling to enabled in the values
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra-cluster/templates/reaper-operator/deployment.yaml
  charts/k8ssandra-cluster/templates/reaper.yaml
  charts/k8ssandra-cluster/values.yaml
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/crds/reaper/reaper.yaml
  charts/restore/Chart.yaml
Labels: complexity: low

#91 [GH 90] make prometheus external url configurable
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra-cluster/templates/prometheus/prometheus.yaml
  charts/k8ssandra-cluster/values.yaml
  charts/k8ssandra/Chart.yaml
  charts/restore/Chart.yaml
Labels: complexity: low

#108 Update doc for k3d _index.md
  docs/content/en/docs/topics/ingress/traefik/k3d-deployment/_index.md
Labels: complexity: low, documentation

#99 Implement unit tests for templates of CassandraDatacenter and Reaper
  Makefile
  go.mod
  go.sum
  tests/template_cassdc_test.go
  tests/template_reaper_test.go
  tests/tests_suite_test.go
  tests/unit/dc_template_unit_test.go
Labels: complexity: medium

#55 Initial attributes for language classification
  .gitattributes
Labels: complexity: low, documentation

#66 Added storageClass and PV size to Helm values for external customisation
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra-cluster/templates/cassdc.yaml
  charts/k8ssandra-cluster/values.yaml
  charts/k8ssandra/Chart.yaml
  charts/restore/Chart.yaml
Labels: doc change needed

#119 run unit tests against PRs
  .github/workflows/main.yaml
Labels: complexity: low

#100 Integration test for helm+kind setup
  Makefile
  go.mod
  tests/bin/cluster.sh
  tests/integration/integration_suite_test.go
  tests/integration/simple_integration_test.go
  tests/unit/template_cassdc_test.go
  tests/unit/template_reaper_test.go
  tests/unit/tests_suite_test.go
Labels: complexity: medium

#129 Include use of --reuse-values flag for helm update
  docs/content/en/docs/topics/provision-a-cluster/_index.md
Labels: complexity: low, doc change needed

#115 #68: added initial Stargate integration
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra-cluster/templates/stargate/service.yaml
  charts/k8ssandra-cluster/templates/stargate/service_monitor.yaml
  charts/k8ssandra-cluster/templates/stargate/stargate.yaml
  charts/k8ssandra-cluster/values.yaml
  charts/k8ssandra/Chart.yaml
  charts/restore/Chart.yaml
  scripts/open-grafana.sh
  scripts/setup-cluster.sh
  scripts/setup-k8ssandra.sh
  scripts/templatize-dashboard.sh
  scripts/update-mcac-dashboards.sh
Labels: complexity: medium, doc change needed, enhancement

#130 Quote version env var value
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra-cluster/templates/stargate/stargate.yaml
  charts/k8ssandra/Chart.yaml
  charts/restore/Chart.yaml
Labels: bug, complexity: low

#134 Cassandra ingress should be enabled by default
  charts/k8ssandra-cluster/values.yaml
Labels: bug, complexity: low

#136 If no Reaper or Medusa is present, do not render empty slices
  charts/k8ssandra-cluster/templates/cassdc.yaml
  tests/unit/template_cassdc_test.go
Labels: complexity: low

#138 Bump chart versions to 0.17.1, add a script
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra/Chart.yaml
  charts/restore/Chart.yaml
  scripts/helm-version.py
Labels: complexity: low
