Repository k8ssandra/k8ssandra, pull requests merged in 2021-04, with the labels that each got.

#615 Add the ability to disable creation of Cassandra cluster
  CHANGELOG.md
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/stargate/service.yaml
  charts/k8ssandra/templates/stargate/stargate.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/template_stargate_test.go
Labels: complexity: low

#614 add volume with pod labels
  CHANGELOG.md
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/utils/cassdc/volumes.go
Labels: complexity: medium, component: backup/restore

#624 [#623] wait for CassandraDatacenters to be gone before exiting
  CHANGELOG.md
  pkg/cleaner/cleaner.go
  pkg/cleaner/cleaner_test.go
Labels: complexity: medium, component: cass-operator

#628 Fix for broken dev quick-start link
  README.md
Labels: doc change needed, documentation

#597 remove jolokia integration
  CHANGELOG.md
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/medusa/medusa-config.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
Labels: complexity: low, component: backup/restore, component: medusa, sprint: 2, sprint: 3

#634 shutdown cluster by default
  CHANGELOG.md
  charts/restore/Chart.yaml
  charts/restore/values.yaml
Labels: complexity: low, component: backup/restore

#645 We should not run integration tests on PRs that do not involve code changes
  .github/workflows/integration-tests.yaml
Labels: complexity: low

#638 Update Management API image locations
  CHANGELOG.md
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
Labels: complexity: medium, sprint: 3

#647 Upgrade to Medusa 0.10.0 and add IT for scale up after restore issue
  CHANGELOG.md
  charts/k8ssandra/values.yaml
  tests/integration/charts/cluster_full_stack.yaml
  tests/integration/charts/cluster_with_medusa_minio.yaml
  tests/integration/charts/cluster_with_medusa_s3.yaml
  tests/integration/charts/cluster_with_reaper.yaml
  tests/integration/charts/cluster_with_stargate.yaml
  tests/integration/charts/cluster_with_stargate_and_monitoring.yaml
  tests/integration/integration_suite_test.go
  tests/integration/steps/integration_steps.go
Labels: complexity: medium, sprint: 3

#658 Upgrade to stargate-v1.0.18
  CHANGELOG.md
  charts/k8ssandra/README.md
  charts/k8ssandra/values.yaml
  docs/content/en/docs/faqs/_index.md
  tests/unit/template_stargate_test.go
Labels: complexity: low, component: stargate, sprint: 3

#581 Enable Medusa local storage option to store the backups
  .github/workflows/integration-tests.yaml
  CHANGELOG-1.2.md
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/medusa/medusa-config.yaml
  charts/k8ssandra/values.yaml
  tests/integration/charts/cluster_with_medusa_local.yaml
  tests/integration/integration_suite_test.go
  tests/unit/template_cassdc_test.go
  tests/unit/template_medusa_config_test.go
Labels: complexity: medium
