Repository k8ssandra/k8ssandra, pull requests merged in 2021-09, with the labels that each got.

#1052 Medusa and reaper operator securityContext
  .gitignore
  charts/cass-operator/Chart.yaml
  charts/cass-operator/values.yaml
  charts/k8ssandra-common/Chart.yaml
  charts/k8ssandra-common/templates/_helpers.tpl
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/reaper/reaper.yaml
  charts/k8ssandra/values.yaml
  charts/medusa-operator/Chart.yaml
  charts/medusa-operator/templates/deployment.yaml
  charts/medusa-operator/values.yaml
  charts/reaper-operator/Chart.yaml
  charts/reaper-operator/templates/deployment.yaml
  charts/reaper-operator/values.yaml
  scripts/delete-crds.sh
  tests/unit/template_cassdc_test.go
  tests/unit/template_medusa_operator_test.go
  tests/unit/template_reaper_operator_test.go
  tests/unit/template_reaper_test.go
  tests/unit/testdata/medusa-operator-security-context-custom-values.yaml
  tests/unit/testdata/reaper-operator-security-context-custom-values.yaml
Labels: enhancement, security

#1095 Temp relax read-only for containers
  charts/cass-operator/values.yaml
  charts/k8ssandra-common/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/utils/cassdc/containers.go
Labels: bug

#1080 k8ssandra-operator sub chart [K8SSAND-819]
  charts/k8ssandra-operator/.helmignore
  charts/k8ssandra-operator/Chart.yaml
  charts/k8ssandra-operator/README.md
  charts/k8ssandra-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_clientconfigs.k8ssandra.io.yaml
  charts/k8ssandra-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_k8ssandraclusters.k8ssandra.io.yaml
  charts/k8ssandra-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_replicatedsecrets.k8ssandra.io.yaml
  charts/k8ssandra-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_stargates.k8ssandra.io.yaml
  charts/k8ssandra-operator/templates/_helpers.tpl
  charts/k8ssandra-operator/templates/configmap.yaml
  charts/k8ssandra-operator/templates/deployment.yaml
  charts/k8ssandra-operator/templates/leader-role.yaml
  charts/k8ssandra-operator/templates/leader-rolebinding.yaml
  charts/k8ssandra-operator/templates/role.yaml
  charts/k8ssandra-operator/templates/rolebinding.yaml
  charts/k8ssandra-operator/templates/serviceaccount.yaml
  charts/k8ssandra-operator/values.yaml
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/values.yaml
  scripts/update-helm-deps.sh
Labels: complexity:medium
