Repository k8ssandra/k8ssandra, pull requests merged in 2021-07, with the labels that each got.

#966 TLS edits and rm obsolete location of prior topic
  docs/content/en/docs/topics/ingress/traefik/tls/_index.md
  docs/content/en/tasks/connect/ingress/_index.md
Labels: complexity:low

#976 Add benchmark info and prereqs in EKS install plus misc GKE edits
  docs/content/en/install/eks/_index.md
  docs/content/en/install/gke/_index.md
Labels: documentation

#975 Volume mount expansion for c*
  CHANGELOG-1.4.md
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  tests/unit/template_cassdc_test.go
Labels: component:cassandra, enhancement, security

#971 NewGenSize: 5G instead of 31G per Michael
  docs/content/en/install/doks/doks.values.yaml
Labels: documentation

#977 Release Notes updates for K8ssandra 1.3.0
  docs/content/en/release-notes/_index.md
Labels: documentation
