Repository k8ssandra/k8ssandra, pull requests merged in 2021-05, with the labels that each got.

#642 Make the stable release workflow dependent on the integration tests one
  .github/workflows/integration-tests-release.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/release-next.yaml
  .github/workflows/release-stable.yaml
  tests/integration/kind/kind_config_3_workers.yaml
Labels: complexity: low, sprint: 3, sprint: 4

#641 Refactor usage of k8s clients in tests
  tests/integration/integration_suite_test.go
  tests/integration/steps/cassdc_client.go
  tests/integration/steps/integration_steps.go
  tests/integration/steps/monitoring_steps.go
  tests/integration/steps/stargate_steps.go
  tests/integration/steps/util.go
Labels: sprint: 4, sprint: 5

#738 Update cass-operator to v1.7.0
  CHANGELOG-1.2.md
  README.md
  charts/cass-operator/Chart.yaml
  charts/cass-operator/README.md
  charts/cass-operator/crds/customresourcedefinition.yaml
  charts/cass-operator/values.yaml
  contrib/upgrade-cass-operator.md
  docs/content/en/docs/topics/ingress/traefik/tls/_index.md
  docs/content/en/release-notes/_index.md
  go.mod
  go.sum
  pkg/cleaner/cleaner.go
  pkg/cleaner/cleaner_test.go
  pkg/cleaner/suite_test.go
  tests/integration/steps/integration_steps.go
  tests/integration/steps/util.go
  tests/unit/template_cassdc_test.go
  tests/unit/utils/cassdc/containers.go
  tests/unit/utils/cassdc/volumes.go
Labels: complexity: medium
