Repository k8ssandra/k8ssandra, pull requests merged in 2021-02, with the labels that each got.

#291 Reaper operator version
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/charts/cass-operator-0.28.0.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.28.0.tgz
  charts/k8ssandra/charts/medusa-operator-0.27.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.28.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.29.0.tgz
  charts/reaper-operator/Chart.yaml
  charts/reaper-operator/values.yaml
Labels: complexity: low, component: reaper-operator

#281 #164: adding correct labels for Prometheus to pick up the Stargate ServiceMonitor
  charts/k8ssandra/templates/stargate/service.yaml
  charts/k8ssandra/templates/stargate/service_monitor.yaml
  charts/k8ssandra/templates/stargate/stargate.yaml
Labels: complexity: low, component: observability, component: stargate

#282 #165: adding initial Grafana dashboard for Stargate
  charts/k8ssandra/dashboards/stargate.json
  charts/k8ssandra/templates/grafana/configmap.yaml
Labels: complexity: low, component: observability, component: stargate, component:grafana

#300 Update Medusa image and refactor properties
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/values.yaml
Labels: complexity: low, component: backup/restore

#294 fixed c* ingress
  charts/k8ssandra/templates/traefik.ingressroutes.yaml
  docs/content/en/docs/topics/ingress/traefik/kind-deployment/kind.config.yaml
Labels: complexity: low, component: ingress

#195 Label consistency and unit-level verification
  charts/k8ssandra-common/templates/_helpers.tpl
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/cassandra/superuser-secret.yaml
  charts/k8ssandra/templates/cleaner/batch_job.yaml
  charts/k8ssandra/templates/cleaner/role.yaml
  charts/k8ssandra/templates/cleaner/role_binding.yaml
  charts/k8ssandra/templates/cleaner/service_account.yaml
  charts/k8ssandra/templates/grafana/dashboards/cassandra-condensed.dashboard-helm-template.yaml
  charts/k8ssandra/templates/grafana/dashboards/overview-with-plugin.dashboard-helm-template.yaml
  charts/k8ssandra/templates/grafana/dashboards/system-metrics.dashboard-helm-template.yaml
  charts/k8ssandra/templates/medusa/medusa-config.yaml
  charts/k8ssandra/templates/medusa/medusa-user-secret.yaml
  charts/k8ssandra/templates/reaper/reaper-jmx-secret.yaml
  charts/k8ssandra/templates/reaper/reaper-user-secret.yaml
  charts/k8ssandra/templates/reaper/reaper.yaml
  charts/k8ssandra/templates/traefik.ingressroutes.yaml
  go.mod
  go.sum
  tests/unit/template_cassdc_test.go
  tests/unit/template_cleaner_test.go
  tests/unit/template_dashboard_test.go
  tests/unit/template_labels_test.go
  tests/unit/template_medusa_user_secret_test.go
  tests/unit/template_prometheus_test.go
  tests/unit/template_reaper_test.go
  tests/unit/template_reaper_user_secret_test.go
  tests/unit/template_superuser_secret_test.go
  tests/unit/tests_suite_test.go
Labels: bug, complexity: medium, priority: p1

#297 Initial stargate auth integration w/ cassdc
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/stargate/stargate-user-secret.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/template_stargate_user_secret_test.go
Labels: auth-support, complexity: medium, component: stargate

#298 set prometheusSpec to a value and add some comments
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/values.yaml
Labels: complexity: low, component: observability

#214 Add FAQ outlining the versions of the high-order components deployed …
  docs/content/en/docs/faqs/_index.md
Labels: complexity: low

#309 Make the reaper image configurable
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/reaper/reaper.yaml
  charts/k8ssandra/values.yaml
Labels: complexity: low, component:reaper

#316 Do not generate secret or set superUsername if auth is disabled
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/cassandra/superuser-secret.yaml
  tests/unit/template_superuser_secret_test.go
Labels: complexity: low

#320 ClusterName defaults to Release.Name
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/cassandra/superuser-secret.yaml
  charts/k8ssandra/templates/medusa/medusa-user-secret.yaml
  charts/k8ssandra/templates/prometheus/service_monitor.yaml
  charts/k8ssandra/templates/reaper/reaper-user-secret.yaml
  charts/k8ssandra/templates/reaper/reaper.yaml
  charts/k8ssandra/templates/stargate/stargate-user-secret.yaml
  charts/k8ssandra/templates/stargate/stargate.yaml
  charts/k8ssandra/templates/traefik.ingressroutes.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
Labels: complexity: low, enhancement, priority: p1

#311 add support for C* 3.11.10 and make it the default version
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
Labels: complexity: low, component: cassandra

#330 don't use subPath mounts and update tests
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  tests/unit/template_cassdc_test.go
Labels: complexity: low, component: backup/restore

#327 Developer documentation for existing scripts
  docs/content/en/docs/topics/dev-tools/_index.md
Labels: complexity: low, documentation, needs-triage, priority: p1

#344 Revert "Developer documentation for existing scripts"
  scripts/README.md
Labels: documentation

#347 Re-fixing #293 for both C* ingress and Stargate C* ingress.
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/ingress.yaml
  charts/k8ssandra/templates/stargate/cassandra-ingress.yaml
  tests/unit/template_cassandra_ingress_test.go
  tests/unit/template_stargate_cassandra_ingress_test.go
  tests/unit/template_stargate_test.go
  tests/unit/tests_suite_test.go
  tests/unit/utils/traefik/tcpRoutes.go
Labels: bug, complexity: low, component: ingress

#357 If stargate, medusa and reaper are disabled, do not render users.
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  tests/unit/template_cassdc_test.go
Labels: complexity: low

#349 Enable Stargate By Default
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/values.yaml
  docs/content/en/docs/getting-started/_index.md
  tests/unit/template_cassandra_ingress_test.go
  tests/unit/template_cassdc_test.go
  tests/unit/template_labels_test.go
  tests/unit/template_stargate_ingress_test.go
  tests/unit/template_stargate_test.go
Labels: complexity: low, component: stargate, documentation

#359 #358: updating versions in docs
  docs/content/en/docs/faqs/_index.md
Labels: complexity: low, documentation

#360 Cassandra heap options (cluster and dc level)
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/README.md
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/values.yaml
  docs/content/en/docs/reference/k8ssandra/_generated.md
  tests/unit/template_cassdc_test.go
Labels: enhancement, priority: p1

#365 Remove Grafana operator CRDs as well as Helm YAML dashboards
  charts/k8ssandra/crds/grafana/grafana.yaml
  charts/k8ssandra/crds/grafana/grafanaDashboard.yaml
  charts/k8ssandra/crds/grafana/grafanaDataSource.yaml
  charts/k8ssandra/templates/grafana/dashboards/cassandra-condensed.dashboard-helm-template.yaml
  charts/k8ssandra/templates/grafana/dashboards/overview-with-plugin.dashboard-helm-template.yaml
  charts/k8ssandra/templates/grafana/dashboards/system-metrics.dashboard-helm-template.yaml
Labels: complexity: low

#370 Removing the pathType as suggested by Michael to resolve backwards co…
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/stargate/ingress.yaml
  tests/unit/template_stargate_ingress_test.go
Labels: complexity: low, component: ingress, component: stargate

#381 Issue 378 main K8ssandra structure re-org.
  docs/content/en/docs/_index.md
  docs/content/en/docs/architecture/_index.md
  docs/content/en/docs/contribution-guidelines/_index.md
  docs/content/en/docs/faqs/_index.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/overview/_index.md
  docs/content/en/docs/reference/_index.md
  docs/content/en/docs/roadmap/_index.md
  docs/content/en/docs/topics/_index.md
  docs/content/en/docs/topics/accessing-services/_index.md
  docs/content/en/docs/topics/cassandra/_index.md
  docs/content/en/docs/topics/ingress/_index.md
  docs/content/en/docs/topics/ingress/traefik/monitoring/_index.md
  docs/content/en/docs/topics/ingress/traefik/repair/_index.md
  docs/content/en/docs/topics/monitoring/_index.md
  docs/content/en/docs/topics/monitoring/grafana-cass-cluster-condensed.png
  docs/content/en/docs/topics/monitoring/grafana-dashboard.png
  docs/content/en/docs/topics/monitoring/grafana-dashboards-default-selected1.png
  docs/content/en/docs/topics/monitoring/grafana-dashboards-icon.png
  docs/content/en/docs/topics/monitoring/grafana-manage-tab-select-default.png
  docs/content/en/docs/topics/monitoring/prometheus-example.png
  docs/content/en/docs/topics/provision-a-cluster/_index.md
  docs/content/en/docs/topics/repair/_index.md
  docs/content/en/docs/topics/repair/reaper-ui.png
  docs/content/en/docs/topics/restore-a-backup/_index.md
  docs/content/en/docs/topics/stargate/_index.md
Labels: documentation

#382 Set the default value of tokens for each supported version
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
Labels: complexity: medium

#372 #361: refactor Stargate ingress configuration
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/cassandra/ingress.yaml
  charts/k8ssandra/templates/reaper/ingress.yaml
  charts/k8ssandra/templates/reaper/reaper-jmx-secret.yaml
  charts/k8ssandra/templates/reaper/reaper-user-secret.yaml
  charts/k8ssandra/templates/reaper/reaper.yaml
  charts/k8ssandra/templates/stargate/cassandra-ingress.yaml
  charts/k8ssandra/templates/stargate/ingress.yaml
  charts/k8ssandra/values.yaml
  tests/integration/simple_integration_test.go
  tests/unit/template_cassandra_ingress_test.go
  tests/unit/template_cassdc_test.go
  tests/unit/template_labels_test.go
  tests/unit/template_reaper_ingress_test.go
  tests/unit/template_reaper_test.go
  tests/unit/template_reaper_user_secret_test.go
  tests/unit/template_stargate_cassandra_ingress_test.go
  tests/unit/template_stargate_ingress_test.go
  tests/unit/template_stargate_test.go
  tests/unit/testdata/cassandra-ingress-nil-host.yaml
  tests/unit/testdata/stargate-cassandra-ingress-empty-host.yaml
  tests/unit/testdata/stargate-cassandra-ingress-nil-host.yaml
  tests/unit/testdata/stargate-ingress-nil-host.yaml
  tests/unit/utils/kubeapi/ingress.go
Labels: complexity: medium, component: ingress, component: stargate, tech-debt

#336 use non-root C* images
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/medusa/medusa-config.yaml
  charts/k8ssandra/templates/medusa/medusa-user-secret.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/template_labels_test.go
  tests/unit/template_medusa_config_test.go
  tests/unit/template_medusa_user_secret_test.go
Labels: complexity: high, component: backup/restore, component: cassandra

#326 generate JMX credentials for C* superuser
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
Labels: auth-support, complexity: medium, component: cassandra

#405 Remove stargate.clusterVersion from values.yaml
  charts/k8ssandra/values.yaml
Labels: complexity: low, component: stargate

#403 Upgrade Stargate and improve doc comments for stargate.image
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/values.yaml
  docs/content/en/docs/faqs/_index.md
  tests/unit/template_stargate_test.go
Labels: component: stargate, enhancement

#398 Allow to run subset of unit tests
  Makefile
Labels: complexity: low, tech-debt

#409 add support for configOverride property
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/testdata/config-override-values.yaml
Labels: complexity: low, component: cassandra

#424 Update the versions included for reaper and medusa.
  docs/content/en/docs/faqs/_index.md
Labels: complexity: low, documentation

#426 Update chart dependencies
  charts/cass-operator/Chart.yaml
  charts/cass-operator/charts/k8ssandra-common-0.28.0.tgz
  charts/cass-operator/charts/k8ssandra-common-0.28.1.tgz
  charts/cass-operator/crds/customresourcedefinition.yaml
  charts/k8ssandra-common/Chart.yaml
  charts/k8ssandra-common/templates/_helpers.tpl
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/charts/cass-operator-0.28.0.tgz
  charts/k8ssandra/charts/cass-operator-0.28.1.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.28.0.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.28.1.tgz
  charts/k8ssandra/charts/medusa-operator-0.27.0.tgz
  charts/k8ssandra/charts/medusa-operator-0.28.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.29.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.29.1.tgz
  charts/medusa-operator/Chart.yaml
  charts/medusa-operator/charts/k8ssandra-common-0.28.0.tgz
  charts/medusa-operator/charts/k8ssandra-common-0.28.1.tgz
  charts/medusa-operator/crds/backup.yaml
  charts/medusa-operator/crds/restore.yaml
  charts/medusa-operator/values.yaml
  charts/reaper-operator/Chart.yaml
  charts/reaper-operator/charts/k8ssandra-common-0.28.0.tgz
  charts/reaper-operator/charts/k8ssandra-common-0.28.1.tgz
Labels: complexity: medium, tech-debt

#429 update reaper-operator version and make resource names more consistent
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/charts/cass-operator-0.28.1.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.28.1.tgz
  charts/k8ssandra/charts/medusa-operator-0.28.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.29.1.tgz
  charts/k8ssandra/charts/reaper-operator-0.30.0.tgz
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/reaper/ingress.yaml
  charts/k8ssandra/templates/reaper/reaper.yaml
  charts/reaper-operator/Chart.yaml
  charts/reaper-operator/values.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/template_reaper_ingress_test.go
Labels: complexity: low

#414 do not generate new passwords if the secrets already exist
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/cassandra/superuser-secret.yaml
  charts/k8ssandra/templates/medusa/medusa-user-secret.yaml
  charts/k8ssandra/templates/reaper/reaper-jmx-secret.yaml
  charts/k8ssandra/templates/reaper/reaper-user-secret.yaml
  charts/k8ssandra/templates/reaper/reaper.yaml
  charts/k8ssandra/templates/stargate/stargate-user-secret.yaml
  charts/k8ssandra/values.yaml
Labels: complexity: high, component: cass-operator

#432 Update name of service routed to by reaper ingress rule
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/reaper/ingress.yaml
  tests/unit/template_reaper_ingress_test.go
Labels: complexity: low, component: ingress, component: reaper-operator, component:reaper

#434 Fix reaper usersecret
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/reaper/reaper.yaml
  tests/unit/template_reaper_test.go
Labels: complexity: medium, component:reaper

#435 make secret name templates consistent
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/reaper/reaper.yaml
Labels: complexity: low

#389 Recorded a new video of the quick cli install for the home page
  docs/content/en/_index.md
Labels: complexity: low, documentation, website

#444 update to v1.6.0
  charts/cass-operator/Chart.yaml
  charts/cass-operator/values.yaml
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/charts/cass-operator-0.28.1.tgz
  charts/k8ssandra/charts/cass-operator-0.29.0.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.28.1.tgz
  charts/k8ssandra/charts/medusa-operator-0.28.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.30.0.tgz
Labels: complexity: low, component: cass-operator

#449 Trademark and various formatting fixes. Redo for C* tasks (point to g…
  docs/content/en/_index.md
  docs/content/en/docs/_index.md
  docs/content/en/docs/architecture/_index.md
  docs/content/en/docs/architecture/backups/_index.md
  docs/content/en/docs/architecture/cassandra/_index.md
  docs/content/en/docs/architecture/monitoring/_index.md
  docs/content/en/docs/architecture/stargate/_index.md
  docs/content/en/docs/contribution-guidelines/_index.md
  docs/content/en/docs/faqs/_index.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/getting-started/developer/_index.md
  docs/content/en/docs/getting-started/site-engineer/_index.md
  docs/content/en/docs/reference/cass-operator/_index.md
  docs/content/en/docs/reference/medusa-operator/_index.md
  docs/content/en/docs/reference/reaper-operator/_index.md
  docs/content/en/docs/roadmap/_index.md
  docs/content/en/docs/topics/_index.md
  docs/content/en/docs/topics/cassandra/_index.md
  docs/content/en/docs/topics/ingress/_index.md
  docs/content/en/docs/topics/ingress/traefik/_index.md
  docs/content/en/docs/topics/ingress/traefik/kind-deployment/_index.md
  docs/content/en/docs/topics/ingress/traefik/monitoring/_index.md
  docs/content/en/docs/topics/ingress/traefik/repair/_index.md
  docs/content/en/docs/topics/monitoring/_index.md
  docs/content/en/docs/topics/provision-a-cluster/_index.md
  docs/content/en/docs/topics/repair/_index.md
  docs/content/en/docs/topics/restore-a-backup/_index.md
  docs/content/en/docs/topics/stargate/_index.md
Labels: documentation

#452 More product name wrangling for Medusa and Reaper.
  docs/content/en/docs/architecture/monitoring/_index.md
  docs/content/en/docs/architecture/repairs/_index.md
  docs/content/en/docs/faqs/_index.md
  docs/content/en/docs/getting-started/site-engineer/_index.md
  docs/content/en/docs/topics/ingress/traefik/repair/_index.md
  docs/content/en/docs/topics/repair/_index.md
  docs/content/en/docs/topics/restore-a-backup/_index.md
Labels: documentation
