Repository k8ssandra/k8ssandra, pull requests merged in 2021-03, with the labels that each got.

#443 update info for containers in C* pods
  docs/content/en/docs/architecture/cassandra/_index.md
Labels: documentation

#471 Update chart properties for backup/restore with Medusa
  docs/content/en/docs/topics/restore-a-backup/_index.md
  docs/content/en/docs/topics/restore-a-backup/backup-restore-values.yaml
Labels: component: backup/restore, documentation

#473 Fix local storage configuration
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/medusa/medusa-config.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/template_medusa_config_test.go
  tests/unit/utils/kubeapi/volumes.go
Labels: complexity: low, component: backup/restore

#497 remove what k8ssandra is not good for section
  docs/content/en/docs/_index.md
Labels: complexity: low, documentation

#498 fix FAQ about installing multiple releases
  docs/content/en/docs/faqs/_index.md
Labels: complexity: low, documentation

#504 Split dashboards into separate configmaps
  CHANGELOG.md
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/condensed-dashboard.yaml
  charts/k8ssandra/templates/cassandra/overview-dashboard.yaml
  charts/k8ssandra/templates/cassandra/system-metrics-dashboard.yaml
  charts/k8ssandra/templates/grafana/configmap.yaml
  charts/k8ssandra/templates/stargate/api-dashboard.yaml
  tests/unit/template_dashboard_test.go
Labels: component:grafana

#419 Helm Repo Release Streams
  .github/workflows/pr-main.yaml
  .github/workflows/release-next.yaml
  .github/workflows/release-stable.yaml
  .gitignore
  CHANGELOG.md
  charts/cass-operator/charts/k8ssandra-common-0.28.1.tgz
  charts/k8ssandra-common/charts/common-1.3.4.tgz
  charts/k8ssandra/charts/cass-operator-0.29.0.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.28.1.tgz
  charts/k8ssandra/charts/kube-prometheus-stack-12.11.3.tgz
  charts/k8ssandra/charts/medusa-operator-0.28.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.30.0.tgz
  charts/medusa-operator/charts/k8ssandra-common-0.28.1.tgz
  charts/reaper-operator/charts/k8ssandra-common-0.28.1.tgz
  docs/content/en/docs/faqs/_index.md
  docs/content/en/docs/topics/restore-a-backup/_index.md
  scripts/install-helm.sh
  scripts/install-yq.sh
  scripts/update-helm-deps.sh
Labels: complexity: high, sprint: 1, tech-debt

#526 Fix Cassandra config clobbering when enabling Medusa
  CHANGELOG.md
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/utils/cassdc/volumes.go
Labels: component: cassandra, component: medusa

#511 Update examples and docs in values.yaml
  CHANGELOG.md
  charts/backup/README.md
  charts/cass-operator/README.md
  charts/k8ssandra-common/README.md
  charts/k8ssandra/README.md
  charts/k8ssandra/values.yaml
  charts/medusa-operator/README.md
  charts/reaper-operator/README.md
  charts/restore/README.md
  docs/content/en/docs/reference/k8ssandra/_generated.md
Labels: documentation

#559 239 dev docs
  CHANGELOG.md
  README.md
  dev-quick-start.md
Labels: complexity: medium, documentation, sprint: 1

#535 Doc for upgrading cass-operator
  contrib/upgrade-cass-operator.md
Labels: complexity: medium, documentation, sprint: 1, sprint: 2

#585 Docs Fix - getting-started Grafana indentation
  docs/content/en/docs/getting-started/_index.md
Labels: documentation

#591 Create webhook secret to ensure cass-operator deployment isn't blocked
  CHANGELOG.md
  charts/cass-operator/Chart.yaml
  charts/cass-operator/templates/deployment.yaml
  charts/cass-operator/templates/webhook-secret.yaml
  charts/k8ssandra/Chart.yaml
Labels: complexity: low

#544 Implement integration tests with the testing package
  .github/workflows/integration-tests.yaml
  Makefile
  dev-quick-start.md
  go.mod
  go.sum
  tests/integration/charts/one_node_cluster_with_medusa_minio.yaml
  tests/integration/charts/one_node_cluster_with_medusa_s3.yaml
  tests/integration/charts/three_nodes_cluster_full_stack.yaml
  tests/integration/charts/three_nodes_cluster_with_reaper.yaml
  tests/integration/charts/three_nodes_cluster_with_stargate.yaml
  tests/integration/charts/three_nodes_cluster_with_stargate_and_monitoring.yaml
  tests/integration/integration_suite_test.go
  tests/integration/scripts/collect_artifacts.sh
  tests/integration/scripts/create_kind_cluster.sh
  tests/integration/secret/medusa_minio_secret.yaml
  tests/integration/simple_integration_test.go
  tests/integration/steps/cassdc_client.go
  tests/integration/steps/integration_steps.go
  tests/integration/steps/medusa_steps.go
  tests/integration/steps/monitoring_steps.go
  tests/integration/steps/reaper_steps.go
  tests/integration/steps/stargate_steps.go
Labels: complexity: high, sprint: 1, sprint: 2, tech-debt

#603 fix indentation in example backup-restore-values.yaml
  CHANGELOG.md
  docs/content/en/docs/topics/restore-a-backup/backup-restore-values.yaml
Labels: component: backup/restore, documentation
