Repository k8ssandra/k8ssandra, pull requests merged in 2021-01, with the labels that each got.

#141 Update Reaper to 2.1.3
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra-cluster/templates/reaper.yaml
  charts/k8ssandra/Chart.yaml
  charts/restore/Chart.yaml
  scripts/helm-version.py
Labels: complexity: low

#133 Deletion job
  .gitignore
  Makefile
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra-cluster/templates/cleaner/batch_job.yaml
  charts/k8ssandra-cluster/templates/cleaner/role.yaml
  charts/k8ssandra-cluster/templates/cleaner/role_binding.yaml
  charts/k8ssandra-cluster/templates/cleaner/service_account.yaml
  charts/k8ssandra-cluster/values.yaml
  charts/k8ssandra/Chart.yaml
  charts/restore/Chart.yaml
  cmd/k8ssandra-client/Dockerfile
  cmd/k8ssandra-client/main.go
  go.mod
  pkg/cleaner/cleaner.go
  pkg/cleaner/cleaner_test.go
  pkg/cleaner/suite_test.go
  tests/unit/template_cassdc_test.go
  tests/unit/template_cleaner_test.go
  tests/unit/template_datasource_test.go
  tests/unit/template_prometheus_test.go
  tests/unit/template_reaper_test.go
  tests/unit/tests_suite_test.go
Labels: complexity: medium

#140 Additional Stargate Related Doc Updates #139
  docs/content/en/docs/architecture/stargate/_index.md
  docs/content/en/docs/faqs/_index.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/reference/backup/_index.md
  docs/content/en/docs/reference/backup/values.yaml
  docs/content/en/docs/reference/k8ssandra-cluster/_index.md
  docs/content/en/docs/reference/k8ssandra-cluster/values.yaml
  docs/content/en/docs/reference/k8ssandra/_index.md
  docs/content/en/docs/reference/k8ssandra/values.yaml
  docs/content/en/docs/reference/restore/_index.md
  docs/content/en/docs/reference/restore/values.yaml
  docs/content/en/docs/topics/accessing-services/stargate/_index.md
Labels: complexity: low, documentation

#162 Property cleanup
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra-cluster/templates/cassdc.yaml
  charts/k8ssandra-cluster/templates/prometheus/service_monitor.yaml
  charts/k8ssandra-cluster/templates/reaper.yaml
  charts/k8ssandra-cluster/templates/stargate/stargate.yaml
  charts/k8ssandra-cluster/templates/traefik.ingressroutes.yaml
  charts/k8ssandra-cluster/values.yaml
  charts/k8ssandra/Chart.yaml
  charts/restore/Chart.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/template_reaper_test.go
Labels: complexity: low

#157 Fix layout issues of home screen cards
  docs/assets/scss/_variables_project.scss
Labels: complexity: low, documentation

#167 remove starter content that is no longer needed
  cassandra/example-cassdc-full.yaml
  cassandra/example-cassdc-minimal.yaml
  cassandra/example-cassdc-three-rack-three-node.yaml
  prometheus/instance.yaml
  prometheus/operator.yaml
  prometheus/service_monitor.yaml
Labels: complexity: low

#161 pod => container in Cassandra pod docs
  docs/content/en/docs/architecture/cassandra/_index.md
Labels: complexity: low, documentation

#177 Version and image target updated
  charts/k8ssandra-cluster/templates/cassdc.yaml
  tests/unit/template_cassdc_test.go
Labels: complexity: low, priority: p1, tech-debt

#180 #174 Adding a small blurb to the docs noting the metric retention per…
  docs/content/en/docs/architecture/monitoring/_index.md
Labels: complexity: low, documentation, priority: p1

#185 do not run as C* user
  charts/backup/Chart.yaml
  charts/k8ssandra-cluster/Chart.yaml
  charts/k8ssandra-cluster/templates/cassdc.yaml
  charts/k8ssandra/Chart.yaml
  charts/restore/Chart.yaml
  tests/unit/template_cassdc_test.go
Labels: bug

#187 Configurable Resources Additions
  charts/k8ssandra-cluster/values.yaml
  tests/unit/template_cassdc_test.go
Labels: complexity: low, documentation

#166 add script to delete CRDS
  scripts/delete-crds.sh
Labels: complexity: low

#206 Inc suggested related links from John Sanda
  docs/content/en/docs/topics/accessing-services/repair/_index.md
Labels: complexity: low

#205 Remove TODOs for now
  docs/content/en/docs/topics/accessing-services/cassandra/_index.md
Labels: complexity: low

#211 fix auth class names
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassdc.yaml
  tests/unit/template_cassdc_test.go
Labels: auth-support

#213 Update medusa-operator image
  charts/k8ssandra/templates/medusa-operator/deployment.yaml
Labels: complexity: low

#150 build and push cleaner image to docker hub
  .github/workflows/build-cleaner.yaml
  Makefile
Labels: complexity: low, priority: p1

#200 Minikube install instructions
  docs/content/en/docs/topics/ingress/traefik/minikube-deployment/_index.md
  docs/content/en/docs/topics/ingress/traefik/minikube-deployment/screenshot.png
  docs/content/en/docs/topics/ingress/traefik/minikube-deployment/traefik-values.yaml
Labels: complexity: low

#208 Configure Cassandra default superuser
  charts/cass-operator/Chart.yaml
  charts/cass-operator/charts/k8ssandra-common-0.26.0.tgz
  charts/cass-operator/charts/k8ssandra-common-0.27.0.tgz
  charts/k8ssandra-common/Chart.yaml
  charts/k8ssandra-common/templates/_helpers.tpl
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/charts/cass-operator-0.26.0.tgz
  charts/k8ssandra/charts/cass-operator-0.27.0.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.27.0.tgz
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/cassandra/superuser-secret.yaml
  charts/k8ssandra/templates/reaper-jmx-secret.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/template_superuser_secret_test.go
Labels: auth-support, component: cassandra

#221 Refactoring to introduce cluster level configs
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/crds/reaper/reaper.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/cassandra/superuser-secret.yaml
  charts/k8ssandra/templates/prometheus/service_monitor.yaml
  charts/k8ssandra/templates/reaper.yaml
  charts/k8ssandra/templates/stargate/stargate.yaml
  charts/k8ssandra/templates/traefik.ingressroutes.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/template_reaper_test.go
  tests/unit/template_superuser_secret_test.go
Labels: complexity: high, component: cassandra, enhancement, priority: p1

#228 Updating text related to the chart consolidation
  docs/content/en/docs/getting-started/_index.md
Labels: complexity: low, documentation

#232 remove obsolete property names
  charts/k8ssandra/values.yaml
Labels: complexity: low, component: cassandra

#241 Remove obsolete cassandra.size property
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/values.yaml
Labels: complexity: low

#243 Return error code if removal failed
  pkg/cleaner/cleaner.go
  pkg/cleaner/cleaner_test.go
Labels: complexity: low

#240 update medusa image
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/medusa-config.yaml
  charts/k8ssandra/values.yaml
Labels: complexity: low, component: backup/restore

#236 #163: add ingress config for Stargate
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/stargate/service.yaml
  charts/k8ssandra/templates/stargate/service_monitor.yaml
  charts/k8ssandra/templates/stargate/stargate.yaml
  charts/k8ssandra/templates/traefik.ingressroutes.yaml
  charts/k8ssandra/values.yaml
  docs/content/en/docs/topics/ingress/traefik/k3d-deployment/_index.md
  docs/content/en/docs/topics/ingress/traefik/k3d-deployment/traefik.values.yaml
  docs/content/en/docs/topics/ingress/traefik/kind-deployment/_index.md
  docs/content/en/docs/topics/ingress/traefik/kind-deployment/kind.config.yaml
  docs/content/en/docs/topics/ingress/traefik/kind-deployment/traefik.values.yaml
  scripts/update-cluster.sh
Labels: complexity: high, component: stargate

#217 Configure with Reaper with Cassandra role
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/reaper/cassandra-user-secret.yaml
  charts/k8ssandra/templates/reaper/reaper-jmx-secret.yaml
  charts/k8ssandra/templates/reaper/reaper.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/template_reaper_test.go
  tests/unit/template_reaper_user_secret_test.go
Labels: auth-support, complexity: medium, component:reaper

#257 need to make sure the enabled flag for kubernetes is set
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/medusa-config.yaml
Labels: complexity: low, component: backup/restore

#242 JVM options heap inclusion
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/values.yaml
  go.mod
  go.sum
  tests/unit/template_cassdc_test.go
Labels: complexity: medium

#237 Add rack support
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/values.yaml
  tests/unit/template_cassdc_test.go
  tests/unit/testdata/racks-affinity-values.yaml
  tests/unit/testdata/racks-no-affinity-values.yaml
Labels: complexity: medium

#268 remove obsolete medusa-operator templates
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/charts/cass-operator-0.27.0.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.27.0.tgz
  charts/k8ssandra/charts/medusa-operator-0.26.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.26.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.27.0.tgz
  charts/k8ssandra/templates/medusa-operator/deployment.yaml
  charts/k8ssandra/templates/medusa-operator/leader_election_role_binding.yaml
  charts/k8ssandra/templates/medusa-operator/role.yaml
  charts/k8ssandra/templates/medusa-operator/role_binding.yaml
  charts/k8ssandra/templates/medusa-operator/service_account.yaml
Labels: complexity: low

#271 update medusa-operator default image
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/charts/cass-operator-0.27.0.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.27.0.tgz
  charts/k8ssandra/charts/medusa-operator-0.26.0.tgz
  charts/k8ssandra/charts/medusa-operator-0.27.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.27.0.tgz
  charts/medusa-operator/Chart.yaml
  charts/medusa-operator/charts/k8ssandra-common-0.27.0.tgz
  charts/medusa-operator/values.yaml
Labels: complexity: low, component: medusa-operator

#274 #265 Add docs mentioning the API deprecation warnings when installing…
  docs/content/en/docs/faqs/_index.md
  docs/content/en/docs/getting-started/_index.md
Labels: complexity: low, documentation

#269 Updated README in the repo root
  README.md
  charts/README.md
Labels: complexity: low, documentation

#276 Some template refactoring to eliminate duplication
  charts/cass-operator/Chart.yaml
  charts/cass-operator/charts/k8ssandra-common-0.27.0.tgz
  charts/cass-operator/charts/k8ssandra-common-0.28.0.tgz
  charts/cass-operator/templates/serviceaccount.yaml
  charts/k8ssandra-common/Chart.yaml
  charts/k8ssandra-common/templates/_helpers.tpl
  charts/k8ssandra/Chart.yaml
  charts/k8ssandra/charts/cass-operator-0.27.0.tgz
  charts/k8ssandra/charts/cass-operator-0.28.0.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.27.0.tgz
  charts/k8ssandra/charts/k8ssandra-common-0.28.0.tgz
  charts/k8ssandra/charts/medusa-operator-0.27.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.27.0.tgz
  charts/k8ssandra/charts/reaper-operator-0.28.0.tgz
  charts/k8ssandra/templates/_helpers.tpl
  charts/k8ssandra/templates/cassandra/cassdc.yaml
  charts/k8ssandra/templates/prometheus/service_monitor.yaml
  charts/k8ssandra/templates/reaper/reaper.yaml
  charts/k8ssandra/templates/stargate/service.yaml
  charts/k8ssandra/templates/stargate/service_monitor.yaml
  charts/k8ssandra/templates/stargate/stargate.yaml
  charts/medusa-operator/Chart.yaml
  charts/medusa-operator/charts/k8ssandra-common-0.27.0.tgz
  charts/medusa-operator/charts/k8ssandra-common-0.28.0.tgz
  charts/medusa-operator/templates/service_account.yaml
  charts/reaper-operator/Chart.yaml
  charts/reaper-operator/charts/k8ssandra-common-0.27.0.tgz
  charts/reaper-operator/charts/k8ssandra-common-0.28.0.tgz
  charts/reaper-operator/templates/service_account.yaml
Labels: complexity: medium

#272 Adding CONTRIBUTING.md file and pull request template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: complexity: low, documentation
